#include<bits/stdc++.h>
using namespace std;
class Book{public:int id;string title,author;bool issued;};
vector<Book>v;
void line(){cout<<string(73,'-')<<"\n";}
void save(){ofstream out("books.txt");for(auto &b:v) out<<b.id<<"|"<<b.title<<"|"<<b.author<<"|"<<b.issued<<"\n";}
void load(){v.clear();ifstream in("books.txt");string s;while(getline(in,s)){if(s.empty()) continue;size_t p1=s.find('|'); if(p1==string::npos) continue; size_t p2=s.find('|',p1+1); if(p2==string::npos) continue; size_t p3=s.find('|',p2+1); if(p3==string::npos) continue; Book b; b.id=stoi(s.substr(0,p1)); b.title=s.substr(p1+1,p2-p1-1); b.author=s.substr(p2+1,p3-p2-1); b.issued=stoi(s.substr(p3+1)); v.push_back(b);} }
void addBook(){cout<<"Enter Book ID: "; int id; if(!(cin>>id)){cin.clear();string tmp;getline(cin,tmp);return;} cin.ignore(numeric_limits<streamsize>::max(),'\n'); cout<<"Enter Title: "; string title; getline(cin,title); cout<<"Enter Author: "; string author; getline(cin,author); Book b; b.id=id; b.title=title; b.author=author; b.issued=false; v.push_back(b); save(); cout<<"Book Added Successfully!\n";}
void viewAll(){ if(v.empty()){cout<<"No books available.\n"; return;} line(); cout<<left<<setw(6)<<"ID"<<setw(30)<<"Title"<<setw(25)<<"Author"<<setw(12)<<"Status\n"; line(); for(auto &b:v){ string t=b.title.size()>28?b.title.substr(0,27)+"..":b.title; string a=b.author.size()>23?b.author.substr(0,22)+"..":b.author; cout<<left<<setw(6)<<b.id<<setw(30)<<t<<setw(25)<<a<<setw(12)<<(b.issued?"Issued":"Available")<<"\n"; } line(); }
void searchBook(){cout<<"Enter Book ID to Search: "; int x; if(!(cin>>x)){cin.clear();string tmp;getline(cin,tmp);return;} for(auto &b:v) if(b.id==x){ line(); cout<<"Book Found:\n"; cout<<"ID: "<<b.id<<"\nTitle: "<<b.title<<"\nAuthor: "<<b.author<<"\nStatus: "<<(b.issued?"Issued":"Available")<<"\n"; line(); return;} cout<<"Book Not Found!\n"; line();}
void issueBook(){cout<<"Enter Book ID to Issue: "; int x; if(!(cin>>x)){cin.clear();string tmp;getline(cin,tmp);return;} for(auto &b:v) if(b.id==x){ if(!b.issued){b.issued=true; save(); cout<<"Book Issued Successfully!\n"; return;} else{cout<<"Book Already Issued!\n"; return;} } cout<<"Book Not Available!\n";}
void returnBook(){cout<<"Enter Book ID to Return: "; int x; if(!(cin>>x)){cin.clear();string tmp;getline(cin,tmp);return;} for(auto &b:v) if(b.id==x){ if(b.issued){b.issued=false; save(); cout<<"Book Returned Successfully!\n"; return;} else{cout<<"Book Is Not Issued!\n"; return;} } cout<<"Book Not Found!\n";}
int main(){ load(); while(true){ cout<<"\n===== Library Management System =====\n"; cout<<"1. Add Book\n2. View All Books\n3. Search Book\n4. Issue Book\n5. Return Book\n0. Exit\n"; cout<<"Enter Choice: "; int ch; if(!(cin>>ch)){cin.clear();string tmp;getline(cin,tmp);continue;} cin.ignore(numeric_limits<streamsize>::max(),'\n'); if(ch==1) addBook(); else if(ch==2) viewAll(); else if(ch==3) searchBook(); else if(ch==4) issueBook(); else if(ch==5) returnBook(); else if(ch==0) break; } }
